networks:
    my-app-network:

volumes:
  node_modules:
services:
  frontend-dev:
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    env_file:
      - ./.env
    ports:
      - "3000:3000"
      - "24678:24678"
    volumes:
      - .:/src
      - node_modules:/src/node_modules
    networks:
        - my-app-network